###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Push Ups",
    "reps": 20,
    "weight": 0,
    "unit": "lbs", 
    "date": "11-25-21"
}

###
GET http://localhost:3000/exercises HTTP/1.1

###
GET http://localhost:3000/exercises/61a2a0307df65958491d2340 HTTP/1.1

###

PUT http://localhost:3000/exercises/61a2a0307df65958491d2340 HTTP/1.1
content-type: application/json

{
    "unit": "kgs"
}

###
DELETE http://localhost:3000/exercises/61a2ae3537c89b7a2b05be05 HTTP/1.1


###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Eternal Sunshine Of The Spotless Mind",
    "year": 2004,
    "language": "English"
}

###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "High Fidelity",
    "year": 2000,
    "language": "English"
}

###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Anchorman",
    "year": 2004,
    "language": "English"
}


###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "No Country For Old Men",
    "year": 2007,
    "language": "English"
}


###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "A Serious Man",
    "year": 2009,
    "language": "English"
}


###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "City Of God",
    "year": 2003,
    "language": "Portuguese"
}

###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Parasite",
    "year": 2019,
    "language": "Korean"
}
