###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Push Ups",
    "reps": 20,
    "weight": 0,
    "unit": "lbs", 
    "date": "11-25-21"
}

###
GET http://localhost:3000/exercises HTTP/1.1

###
GET http://localhost:3000/exercises/61a2a0307df65958491d2340 HTTP/1.1

###

PUT http://localhost:3000/exercises/61a2a0307df65958491d2340 HTTP/1.1
content-type: application/json

{
    "unit": "kgs"
}

###
DELETE http://localhost:3000/exercises/61a2ae3537c89b7a2b05be05 HTTP/1.1

